# defines the git repositroy to use, options:
# "CODECOMMIT" - will create a new codecommit repo with name specified in repoName
# "CODECOMMIT_PROVIDED" - will expect a codecommit repository in the account with name specified in repoName
# "GITHUB" - will use an existing codestar connection for GitHub source, checkout README.MD, for instructions
repoType: GITHUB
# the repo where the pipeline should pull its source from
repoName: mlops-at-edge-for-quality-inspection
# the CodestarConnectionArn for your GitHub repository
githubConnectionArn: arn:aws:codestar-connections:eu-west-1:097242523850:connection/b41654c4-fd9d-4be9-9c91-b1fd12b0889a
# the GitHub repo owner
githubRepoOwner: rotmi
# the git branch to use
branchName: main
